// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defs.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	defs.proto

It has these top-level messages:
	Payload
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Payload) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Payload)(nil), "rpc.Payload")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Fetch service

type FetchClient interface {
	Capitalize(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
}

type fetchClient struct {
	cc *grpc.ClientConn
}

func NewFetchClient(cc *grpc.ClientConn) FetchClient {
	return &fetchClient{cc}
}

func (c *fetchClient) Capitalize(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/rpc.Fetch/Capitalize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fetch service

type FetchServer interface {
	Capitalize(context.Context, *Payload) (*Payload, error)
}

func RegisterFetchServer(s *grpc.Server, srv FetchServer) {
	s.RegisterService(&_Fetch_serviceDesc, srv)
}

func _Fetch_Capitalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchServer).Capitalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Fetch/Capitalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchServer).Capitalize(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fetch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Fetch",
	HandlerType: (*FetchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capitalize",
			Handler:    _Fetch_Capitalize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs.proto",
}

func init() { proto.RegisterFile("defs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x4d, 0x2b,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0xd2, 0xe5, 0x62, 0x0f,
	0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60,
	0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x8d, 0x8c, 0xb9, 0x58, 0xdd, 0x52, 0x4b, 0x92, 0x33,
	0x84, 0xb4, 0xb8, 0xb8, 0x9c, 0x13, 0x0b, 0x32, 0x4b, 0x12, 0x73, 0x32, 0xab, 0x52, 0x85, 0x78,
	0xf4, 0x8a, 0x0a, 0x92, 0xf5, 0xa0, 0x06, 0x49, 0xa1, 0xf0, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xf6,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x16, 0x22, 0x0e, 0x3f, 0x7d, 0x00, 0x00, 0x00,
}
